=== IvanKharitanovich/XMLParserProject/test/resources/data/medicins.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/medicins"
        xmlns:tns="http://www.example.com/medicins"
        elementFormDefault="qualified">
    <element name="medicins">
        <complexType>
            <sequence>
                <element name="medicine"
                         type="tns:Medicine"
                         minOccurs="1"
                         maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
    <complexType name="Medicine">
        <sequence>
            <element name="name" type="string"/>
            <element name="organisationName" type="string"/>
            <element name="group" type="tns:Group"/>
            <element name="analogs"
                     minOccurs="0"
                     maxOccurs="unbounded">
                <simpleType>
                    <list itemType="string"/>
                </simpleType>
            </element>
            <element name="version" type="tns:Version"/>
            <element name="issueDate" type="date"/>
            <element name="expirationDate" type="date"/>
            <element name="registerOrganisationName" type="string"/>
            <element name="package" type="tns:Package"/>
            <element name="dosage" type="tns:Dosage"/>
        </sequence>
        <attribute name="medicineId" type="tns:MedicineId" use="required"/>
        <attribute name="recipeStatusNeeded" use="optional" default="true">
            <simpleType>
                <restriction base="string">
                    <enumeration value="true"/>
                    <enumeration value="false"/>
                </restriction>
            </simpleType>
        </attribute>
    </complexType>

    <simpleType name="MedicineId">
        <restriction base="ID">
            <pattern value="([A-Z])[0-9]{5,10}"/>
        </restriction>
    </simpleType>

    <simpleType name="Group">
        <restriction base="string">
            <enumeration value="ANALGESICS"/>
            <enumeration value="ANTIBIOTIC"/>
            <enumeration value="ANTISEPTIC"/>
            <enumeration value="HORMONE"/>
            <enumeration value="STIMULANTS"/>
        </restriction>
    </simpleType>

    <simpleType name="Version">
        <restriction base="string">
            <enumeration value="TABLET"/>
            <enumeration value="LIQUID"/>
            <enumeration value="CAPSULES"/>
            <enumeration value="DROPS"/>
            <enumeration value="INJECTIONS"/>
        </restriction>
    </simpleType>

    <complexType name="Package">
        <sequence>
            <element name="packageType" type="tns:PackageType"/>
            <element name="amount" type="double"/>
            <element name="price" type="decimal"/>
        </sequence>
    </complexType>

    <simpleType name="PackageType">
        <restriction base="string">
            <enumeration value="BOTTLES"/>
            <enumeration value="BLISTER_PACK"/>
        </restriction>
    </simpleType>

    <complexType name="Dosage">
        <sequence>
            <element name="dosageAmount" type="double"/>
            <element name="frequency" type="tns:Frequency"/>
        </sequence>
    </complexType>

    <complexType name="Frequency">
        <sequence>
            <element name="days" type="int"/>
            <element name="perDay" type="int"/>
        </sequence>
    </complexType>
</schema>

=== IvanKharitanovich/XMLParserProject/test/resources/data/medicins.xml
<?xml version="1.0" encoding="UTF-8"?>
<medicins xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns="http://www.example.com/medicins"
          xsi:schemaLocation="http://www.example.com/medicins medicins.xsd">
    <medicine medicineId="A0000000001" recipeStatusNeeded="true">
        <name>Humuletine</name>
        <organisationName>DPV44</organisationName>
        <group>ANALGESICS</group>
        <analogs>Retrolog,Ocunide,Demelinum</analogs>
        <version>TABLET</version>
        <issueDate>2012-09-09</issueDate>
        <expirationDate>2020-02-05</expirationDate>
        <registerOrganisationName>STUDOID</registerOrganisationName>
        <package>
            <packageType>BOTTLES</packageType>
            <amount>100</amount>
            <price>25</price>
        </package>
        <dosage>
            <dosageAmount>100</dosageAmount>
            <frequency>
                <days>7</days>
                <perDay>3</perDay>
            </frequency>
        </dosage>
    </medicine>
    <medicine medicineId="A0000000002" recipeStatusNeeded="true">
        <name>Liosulin</name>
        <organisationName>DPV44</organisationName>
        <group>ANALGESICS</group>
        <analogs></analogs>
        <version>TABLET</version>
        <issueDate>2012-09-09</issueDate>
        <expirationDate>2020-02-05</expirationDate>
        <registerOrganisationName>STUDOID</registerOrganisationName>
        <package>
            <packageType>BOTTLES</packageType>
            <amount>100</amount>
            <price>25</price>
        </package>
        <dosage>
            <dosageAmount>100</dosageAmount>
            <frequency>
                <days>7</days>
                <perDay>3</perDay>
            </frequency>
        </dosage>
    </medicine>
    <medicine medicineId="A0000000003" recipeStatusNeeded="true">
        <name>Diazeprazole</name>
        <organisationName>DPV44</organisationName>
        <group>ANALGESICS</group>
        <analogs>Sanctupen,Omebax</analogs>
        <version>TABLET</version>
        <issueDate>2012-09-09</issueDate>
        <expirationDate>2020-02-05</expirationDate>
        <registerOrganisationName>STUDOID</registerOrganisationName>
        <package>
            <packageType>BOTTLES</packageType>
            <amount>100</amount>
            <price>25</price>
        </package>
        <dosage>
            <dosageAmount>100</dosageAmount>
            <frequency>
                <days>7</days>
                <perDay>3</perDay>
            </frequency>
        </dosage>
    </medicine>
    <medicine medicineId="A0000000004" recipeStatusNeeded="true">
        <name>Humuphine</name>
        <organisationName>DPV44</organisationName>
        <group>ANALGESICS</group>
        <analogs>Retrolog,Ocunide,Demelinum</analogs>
        <version>TABLET</version>
        <issueDate>2012-09-09</issueDate>
        <expirationDate>2020-02-05</expirationDate>
        <registerOrganisationName>STUDOID</registerOrganisationName>
        <package>
            <packageType>BOTTLES</packageType>
            <amount>100</amount>
            <price>25</price>
        </package>
        <dosage>
            <dosageAmount>100</dosageAmount>
            <frequency>
                <days>7</days>
                <perDay>3</perDay>
            </frequency>
        </dosage>
    </medicine>
    <medicine medicineId="A0000000005" recipeStatusNeeded="true">
        <name>Sanctunitol</name>
        <organisationName>DPV44</organisationName>
        <group>ANALGESICS</group>
        <analogs>Retrolog,Ocunide,Demelinum</analogs>
        <version>TABLET</version>
        <issueDate>2012-09-09</issueDate>
        <expirationDate>2020-02-05</expirationDate>
        <registerOrganisationName>STUDOID</registerOrganisationName>
        <package>
            <packageType>BOTTLES</packageType>
            <amount>100</amount>
            <price>25</price>
        </package>
        <dosage>
            <dosageAmount>100</dosageAmount>
            <frequency>
                <days>7</days>
                <perDay>3</perDay>
            </frequency>
        </dosage>
    </medicine>
    <medicine medicineId="A0000000006" recipeStatusNeeded="true">
        <name>Aldofranil</name>
        <organisationName>DPV44</organisationName>
        <group>ANALGESICS</group>
        <analogs>Retrolog,Ocunide,Demelinum</analogs>
        <version>TABLET</version>
        <issueDate>2012-09-09</issueDate>
        <expirationDate>2020-02-05</expirationDate>
        <registerOrganisationName>STUDOID</registerOrganisationName>
        <package>
            <packageType>BOTTLES</packageType>
            <amount>100</amount>
            <price>25</price>
        </package>
        <dosage>
            <dosageAmount>100</dosageAmount>
            <frequency>
                <days>7</days>
                <perDay>3</perDay>
            </frequency>
        </dosage>
    </medicine>
    <medicine medicineId="A0000000007" recipeStatusNeeded="true">
        <name>Carbitaine</name>
        <organisationName>DPV44</organisationName>
        <group>ANALGESICS</group>
        <analogs>Retrolog,Ocunide,Demelinum</analogs>
        <version>TABLET</version>
        <issueDate>2012-09-09</issueDate>
        <expirationDate>2020-02-05</expirationDate>
        <registerOrganisationName>STUDOID</registerOrganisationName>
        <package>
            <packageType>BOTTLES</packageType>
            <amount>100</amount>
            <price>25</price>
        </package>
        <dosage>
            <dosageAmount>100</dosageAmount>
            <frequency>
                <days>7</days>
                <perDay>3</perDay>
            </frequency>
        </dosage>
    </medicine>
    <medicine medicineId="A0000000008" recipeStatusNeeded="true">
        <name>Prepaban Azapitant</name>
        <organisationName>DPV44</organisationName>
        <group>ANALGESICS</group>
        <analogs>Retrolog,Ocunide,Demelinum</analogs>
        <version>TABLET</version>
        <issueDate>2012-09-09</issueDate>
        <expirationDate>2020-02-05</expirationDate>
        <registerOrganisationName>STUDOID</registerOrganisationName>
        <package>
            <packageType>BOTTLES</packageType>
            <amount>100</amount>
            <price>25</price>
        </package>
        <dosage>
            <dosageAmount>100</dosageAmount>
            <frequency>
                <days>7</days>
                <perDay>3</perDay>
            </frequency>
        </dosage>
    </medicine>
    <medicine medicineId="A0000000009" recipeStatusNeeded="true">
        <name>Olsatriene Fragpan</name>
        <organisationName>DPV44</organisationName>
        <group>ANALGESICS</group>
        <analogs>Retrolog,Ocunide,Demelinum</analogs>
        <version>TABLET</version>
        <issueDate>2012-09-09</issueDate>
        <expirationDate>2020-02-05</expirationDate>
        <registerOrganisationName>STUDOID</registerOrganisationName>
        <package>
            <packageType>BOTTLES</packageType>
            <amount>100</amount>
            <price>25</price>
        </package>
        <dosage>
            <dosageAmount>100</dosageAmount>
            <frequency>
                <days>7</days>
                <perDay>3</perDay>
            </frequency>
        </dosage>
    </medicine>
    <medicine medicineId="A0000000010" recipeStatusNeeded="true">
        <name>Protopen Acebugestrel</name>
        <organisationName>DPV44</organisationName>
        <group>ANALGESICS</group>
        <analogs>Retrolog,Ocunide,Demelinum</analogs>
        <version>TABLET</version>
        <issueDate>2012-09-09</issueDate>
        <expirationDate>2020-02-05</expirationDate>
        <registerOrganisationName>STUDOID</registerOrganisationName>
        <package>
            <packageType>BOTTLES</packageType>
            <amount>100</amount>
            <price>25</price>
        </package>
        <dosage>
            <dosageAmount>100</dosageAmount>
            <frequency>
                <days>7</days>
                <perDay>3</perDay>
            </frequency>
        </dosage>
    </medicine>
    <medicine medicineId="A0000000011" recipeStatusNeeded="true">
        <name>Abinase</name>
        <organisationName>DPV44</organisationName>
        <group>ANALGESICS</group>
        <analogs>Retrolog,Ocunide,Demelinum</analogs>
        <version>TABLET</version>
        <issueDate>2012-09-09</issueDate>
        <expirationDate>2020-02-05</expirationDate>
        <registerOrganisationName>STUDOID</registerOrganisationName>
        <package>
            <packageType>BOTTLES</packageType>
            <amount>100</amount>
            <price>25</price>
        </package>
        <dosage>
            <dosageAmount>100</dosageAmount>
            <frequency>
                <days>7</days>
                <perDay>3</perDay>
            </frequency>
        </dosage>
    </medicine>
    <medicine medicineId="A0000000012" recipeStatusNeeded="true">
        <name>Duratate</name>
        <organisationName>DPV44</organisationName>
        <group>ANALGESICS</group>
        <analogs>Retrolog,Ocunide,Demelinum</analogs>
        <version>TABLET</version>
        <issueDate>2012-09-09</issueDate>
        <expirationDate>2020-02-05</expirationDate>
        <registerOrganisationName>STUDOID</registerOrganisationName>
        <package>
            <packageType>BOTTLES</packageType>
            <amount>100</amount>
            <price>25</price>
        </package>
        <dosage>
            <dosageAmount>100</dosageAmount>
            <frequency>
                <days>7</days>
                <perDay>3</perDay>
            </frequency>
        </dosage>
    </medicine>
